
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace HazelCE.Editor {
    using System;
    using Terminal.Gui;
    
    
    public partial class CE : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greenOnBlack2;
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme edit2;
        
        private Terminal.Gui.ColorScheme bg;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.ColorScheme command2;
        
        private Terminal.Gui.Label label2;
        
        private Terminal.Gui.TextView textView;
        
        private Terminal.Gui.Label label3;
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.TextField textField;
        
        private Terminal.Gui.MenuBar menuBar;
        
        private Terminal.Gui.MenuBarItem fileF9Menu;
        
        private Terminal.Gui.MenuItem newMenuItem;
        
        private Terminal.Gui.MenuItem openMenuItem;
        
        private Terminal.Gui.MenuItem saveMenuItem;
        
        private Terminal.Gui.MenuItem openInExplorerMenuItem;
        
        private Terminal.Gui.MenuBarItem clipboardMenu;
        
        private Terminal.Gui.MenuItem copyMenuItem;
        
        private Terminal.Gui.MenuItem cutMenuItem;
        
        private Terminal.Gui.MenuItem pasteMenuItem;
        
        private Terminal.Gui.MenuBarItem editorMenu;
        
        private Terminal.Gui.MenuItem pluginsMenuItem;
        
        private Terminal.Gui.MenuItem confighceditorMenuItem;
        
        private Terminal.Gui.MenuItem reloadMenuItem;
        
        private Terminal.Gui.MenuItem openEditorFolderMenuItem;
        
        private void InitializeComponent() {
            this.menuBar = new Terminal.Gui.MenuBar();
            this.textField = new Terminal.Gui.TextField();
            this.label = new Terminal.Gui.Label();
            this.label3 = new Terminal.Gui.Label();
            this.textView = new Terminal.Gui.TextView();
            this.label2 = new Terminal.Gui.Label();
            this.greenOnBlack2 = new Terminal.Gui.ColorScheme();
            this.greenOnBlack2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Gray);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.edit2 = new Terminal.Gui.ColorScheme();
            this.edit2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.edit2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.edit2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.edit2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.edit2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.bg = new Terminal.Gui.ColorScheme();
            this.bg.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.DarkGray);
            this.bg.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.bg.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.bg.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.bg.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.command2 = new Terminal.Gui.ColorScheme();
            this.command2.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.command2.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.command2.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.command2.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.command2.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.edit2;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.White;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "HazelCE Editor";
            this.label2.Width = 3;
            this.label2.Height = 1;
            this.label2.X = 114;
            this.label2.Y = 0;
            this.label2.Data = "label2";
            this.label2.Text = "HeyaFi";
            this.label2.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.Add(this.label2);
            this.textView.Width = 118;
            this.textView.Height = 24;
            this.textView.X = 0;
            this.textView.Y = 1;
            this.textView.ColorScheme = this.edit2;
            this.textView.AllowsTab = true;
            this.textView.AllowsReturn = true;
            this.textView.WordWrap = false;
            this.textView.Data = "textView";
            this.textView.Text = "";
            this.textView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textView);
            this.label3.Width = 4;
            this.label3.Height = 1;
            this.label3.X = 100;
            this.label3.Y = 25;
            this.label3.ColorScheme = this.tgDefault;
            this.label3.Data = "label3";
            this.label3.Text = "HazelCE.Editor.exe";
            this.label3.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.Add(this.label3);
            this.label.Width = 11;
            this.label.Height = 1;
            this.label.X = 0;
            this.label.Y = 26;
            this.label.Data = "label";
            this.label.Text = "Command Line:";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.textField.Width = 117;
            this.textField.Height = 1;
            this.textField.X = 0;
            this.textField.Y = 27;
            this.textField.ColorScheme = this.command2;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.menuBar.Width = Dim.Fill(0);
            this.menuBar.Height = 4;
            this.menuBar.X = 0;
            this.menuBar.Y = 0;
            this.menuBar.ColorScheme = this.edit2;
            this.menuBar.Data = "menuBar";
            this.menuBar.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.fileF9Menu = new Terminal.Gui.MenuBarItem();
            this.fileF9Menu.Title = "_File (F9)";
            this.newMenuItem = new Terminal.Gui.MenuItem();
            this.newMenuItem.Title = "New";
            this.newMenuItem.Data = "newMenuItem";
            this.newMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741902u));
            this.openMenuItem = new Terminal.Gui.MenuItem();
            this.openMenuItem.Title = "Open";
            this.openMenuItem.Data = "openMenuItem";
            this.openMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741903u));
            this.saveMenuItem = new Terminal.Gui.MenuItem();
            this.saveMenuItem.Title = "Save";
            this.saveMenuItem.Data = "saveMenuItem";
            this.saveMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741907u));
            this.openInExplorerMenuItem = new Terminal.Gui.MenuItem();
            this.openInExplorerMenuItem.Title = "Open in Explorer";
            this.openInExplorerMenuItem.Data = "openInExplorerMenuItem";
            this.openInExplorerMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741893u));
            this.clipboardMenu = new Terminal.Gui.MenuBarItem();
            this.clipboardMenu.Title = "Clipboard";
            this.copyMenuItem = new Terminal.Gui.MenuItem();
            this.copyMenuItem.Title = "Copy";
            this.copyMenuItem.Data = "copyMenuItem";
            this.copyMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741891u));
            this.cutMenuItem = new Terminal.Gui.MenuItem();
            this.cutMenuItem.Title = "Cut";
            this.cutMenuItem.Data = "cutMenuItem";
            this.cutMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741912u));
            this.pasteMenuItem = new Terminal.Gui.MenuItem();
            this.pasteMenuItem.Title = "Paste";
            this.pasteMenuItem.Data = "pasteMenuItem";
            this.pasteMenuItem.Shortcut = ((Terminal.Gui.Key)(1073741910u));
            this.clipboardMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.copyMenuItem,
                    this.cutMenuItem,
                    this.pasteMenuItem};
            this.fileF9Menu.Children = new Terminal.Gui.MenuItem[] {
                    this.newMenuItem,
                    this.openMenuItem,
                    this.saveMenuItem,
                    this.openInExplorerMenuItem,
                    this.clipboardMenu};
            this.editorMenu = new Terminal.Gui.MenuBarItem();
            this.editorMenu.Title = "Editor";
            this.pluginsMenuItem = new Terminal.Gui.MenuItem();
            this.pluginsMenuItem.Title = "Plugins";
            this.pluginsMenuItem.Data = "pluginsMenuItem";
            this.confighceditorMenuItem = new Terminal.Gui.MenuItem();
            this.confighceditorMenuItem.Title = "Config.hceditor";
            this.confighceditorMenuItem.Data = "confighceditorMenuItem";
            this.reloadMenuItem = new Terminal.Gui.MenuItem();
            this.reloadMenuItem.Title = "Reload";
            this.reloadMenuItem.Data = "reloadMenuItem";
            this.openEditorFolderMenuItem = new Terminal.Gui.MenuItem();
            this.openEditorFolderMenuItem.Title = "Open Editor Folder";
            this.openEditorFolderMenuItem.Data = "openEditorFolderMenuItem";
            this.editorMenu.Children = new Terminal.Gui.MenuItem[] {
                    this.pluginsMenuItem,
                    this.confighceditorMenuItem,
                    this.reloadMenuItem,
                    this.openEditorFolderMenuItem};
            this.menuBar.Menus = new Terminal.Gui.MenuBarItem[] {
                    this.fileF9Menu,
                    this.editorMenu};
            this.Add(this.menuBar);
        }
    }
}
